# Generated by Django 5.1.5 on 2025-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Published', models.DateField()),
            ],
        ),
    ]
