# Generated by Django 5.1.5 on 2025-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='books',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
